# This GitHub workflow validates Bundle config (ML resource config and more)
# defined under mlops-bundles-demo/databricks-resources/*
# and mlops-bundles-demo/bundle.yml, when PRs are merged into the main branch
name: Bundle validation for gh-mlops-stack-dab

on:
  workflow_dispatch:
  pull_request_target:

defaults:
  run:
    working-directory: ./mlops-bundles-demo/


jobs:
  staging:
    concurrency: mlops-bundle-demo-staging-bundle-job
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - uses: databricks/setup-cli@main
      - name: Validate Bundle For Staging Environment
        id: validate
        env:
          DATABRICKS_TOKEN: ${{secrets.mlops_staging}}
          DATABRICKS_BUNDLE_ENV: staging
        run: |
          databricks bundle validate -e staging > ../validate_output.txt
      

  prod:
    concurrency: gh-mlops-stack-dab-prod-bundle-job
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - uses: databricks/setup-cli@main
      - name: Validate Bundle For Prod Environment
        id: validate
        env:
          DATABRICKS_TOKEN: ${{secrets.mlops_prod}}
          DATABRICKS_BUNDLE_ENV: prod
        run: |
          databricks bundle validate -e prod > ../validate_output.txt
      
